// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbauth/pb/auth_token_info.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthTokenInfo struct {
	AppId                uint64   `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Uin                  uint64   `protobuf:"varint,2,opt,name=uin,proto3" json:"uin,omitempty"`
	OwnerUin             uint64   `protobuf:"varint,3,opt,name=ownerUin,proto3" json:"ownerUin,omitempty"`
	ReqId                string   `protobuf:"bytes,4,opt,name=reqId,proto3" json:"reqId,omitempty"`
	InstanceId           string   `protobuf:"bytes,5,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Region               string   `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	CreateTime           uint64   `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,10,opt,name=extraInfo,proto3" json:"extraInfo,omitempty"`
	TokenType            uint32   `protobuf:"varint,11,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	RandNum              uint32   `protobuf:"varint,12,opt,name=randNum,proto3" json:"randNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenInfo) Reset()         { *m = AuthTokenInfo{} }
func (m *AuthTokenInfo) String() string { return proto.CompactTextString(m) }
func (*AuthTokenInfo) ProtoMessage()    {}
func (*AuthTokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1200ce7bcf192bff, []int{0}
}

func (m *AuthTokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenInfo.Unmarshal(m, b)
}
func (m *AuthTokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenInfo.Marshal(b, m, deterministic)
}
func (m *AuthTokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenInfo.Merge(m, src)
}
func (m *AuthTokenInfo) XXX_Size() int {
	return xxx_messageInfo_AuthTokenInfo.Size(m)
}
func (m *AuthTokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenInfo proto.InternalMessageInfo

func (m *AuthTokenInfo) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *AuthTokenInfo) GetUin() uint64 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *AuthTokenInfo) GetOwnerUin() uint64 {
	if m != nil {
		return m.OwnerUin
	}
	return 0
}

func (m *AuthTokenInfo) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *AuthTokenInfo) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *AuthTokenInfo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *AuthTokenInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthTokenInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthTokenInfo) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *AuthTokenInfo) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

func (m *AuthTokenInfo) GetTokenType() uint32 {
	if m != nil {
		return m.TokenType
	}
	return 0
}

func (m *AuthTokenInfo) GetRandNum() uint32 {
	if m != nil {
		return m.RandNum
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthTokenInfo)(nil), "pb.AuthTokenInfo")
}

func init() { proto.RegisterFile("dbauth/pb/auth_token_info.proto", fileDescriptor_1200ce7bcf192bff) }

var fileDescriptor_1200ce7bcf192bff = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0x95, 0xb4, 0x4d, 0x9b, 0x83, 0x4a, 0xc8, 0x42, 0xe8, 0x84, 0x10, 0x44, 0x4c, 0x99,
	0xe8, 0xc0, 0x13, 0x30, 0x66, 0x61, 0x88, 0xc2, 0x5c, 0x39, 0xf5, 0x95, 0x5a, 0x28, 0x67, 0xe3,
	0x38, 0x2a, 0x3c, 0x25, 0xaf, 0x84, 0xec, 0xf4, 0x6f, 0x4a, 0xbe, 0xef, 0x53, 0x72, 0xf6, 0xc1,
	0x93, 0x6a, 0xe5, 0xe0, 0x77, 0x2b, 0xdb, 0xae, 0xc2, 0x73, 0xed, 0xcd, 0x17, 0xf1, 0x5a, 0xf3,
	0xd6, 0xbc, 0x58, 0x67, 0xbc, 0x11, 0xa9, 0x6d, 0x9f, 0xff, 0x52, 0x58, 0xbe, 0x0d, 0x7e, 0xd7,
	0x84, 0x58, 0xf1, 0xd6, 0x88, 0x5b, 0x98, 0x49, 0x6b, 0x2b, 0x85, 0x49, 0x91, 0x94, 0xd3, 0x7a,
	0x04, 0x71, 0x03, 0x93, 0x41, 0x33, 0xa6, 0xd1, 0x85, 0x57, 0x71, 0x0f, 0x0b, 0xb3, 0x67, 0x72,
	0x1f, 0x9a, 0x71, 0x12, 0xf5, 0x89, 0xc3, 0x3f, 0x1c, 0x7d, 0x57, 0x0a, 0xa7, 0x45, 0x52, 0xe6,
	0xf5, 0x08, 0xe2, 0x11, 0x40, 0x73, 0xef, 0x25, 0x6f, 0xa8, 0x52, 0x38, 0x8b, 0xe9, 0xc2, 0x88,
	0x3b, 0xc8, 0x1c, 0x7d, 0x6a, 0xc3, 0x98, 0xc5, 0x76, 0xa0, 0x30, 0x69, 0xe8, 0xc9, 0xb1, 0xec,
	0x08, 0xe7, 0xb1, 0x9c, 0x38, 0x34, 0x2b, 0xfb, 0x7e, 0x6f, 0x9c, 0xc2, 0xc5, 0xd8, 0x8e, 0x1c,
	0xe6, 0x6d, 0x1c, 0x49, 0x4f, 0x8d, 0xee, 0x08, 0xf3, 0x78, 0xc6, 0x0b, 0x23, 0x1e, 0x20, 0xa7,
	0x1f, 0xef, 0x64, 0xb8, 0x36, 0x42, 0xfc, 0xf8, 0x2c, 0x42, 0x8d, 0x1b, 0x6b, 0x7e, 0x2d, 0xe1,
	0x55, 0x91, 0x94, 0xcb, 0xfa, 0x2c, 0x04, 0xc2, 0xdc, 0x49, 0x56, 0xef, 0x43, 0x87, 0xd7, 0xb1,
	0x1d, 0xb1, 0xcd, 0xe2, 0x72, 0x5f, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x43, 0xce, 0x7f,
	0x7f, 0x01, 0x00, 0x00,
}
